spring:
  profiles:
    active: local
---

spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    show_sql: false
    database: H2
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  h2:
    console:
      enabled: true
      path: "/h2-console"

testconfig:
  projectName: Customer reward portal
  appOwner: Babatunde Alaraje
---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/portaldb
    username: root
    password: password
  jpa:
    show_sql: false
    database: MYSQL
    generate-ddl: true
  security:
    user:
      password: test

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /management

configuration:
  projectName: Customer reward portal
  owner: Babatunde Alaraje
