export const ACTION_TYPES = {
  GET_CUSTOMER_TRANSACTIONS: "ALL_TRANSACTION",
  GET_CUSTOMER_TRANSACTION_BY_MONTH: "GET_CUSTOMER_TRANSACTION_BY_MONTH",
  GET_ALL_CUSTOMERS: "GET_ALL_CUSTOMERS",
  UPDATE_CUSTOMER: "UPDATE_CUSTOMER",
  UPDATE_MONTH: "UPDATE_UPDATE",
};
